version: '3.6'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    container_name: zookeeper
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    container_name: kafka
    networks:
      - kafka_network


  action-monitor:
    image: action-monitor:2.0.0
    environment:
      SPRING_PROFILES_ACTIVE: container
    ports:
      - '8080:8080'
    networks:
      - kafka_network
    depends_on:
      - kafka


  react-client:
    image: react-client:3.0.0
    ports:
      - '3000:3000'
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_docker_example_net
